name: Notify Fork on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Sync in Fork
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.UPSTREAM_PAT }}" \
            https://api.github.com/repos/ezraatmnda/discord-hq/dispatches \
            -d '{"event_type": "upstream_push"}'