name: Sync Fork

on:
  repository_dispatch:
    types: [upstream_push]
  workflow_dispatch: # Allows manual trigger from GitHub UI for testing

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history so branches can sync properly
    
      - name: Sync GitHub Repository
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "btdugm-stack/virtual-warga-discord"
          source_branch: "main"
          destination_branch: "production"
          github_token: ${{ secrets.PAT_TOKEN }}
