name: Sync Fork

on:
  repository_dispatch:
    types: [upstream_push]
  workflow_dispatch: # Allows manual trigger from GitHub UI for testing

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Fork
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "btdugm-stack/virtual-warga-discord"
          source_branch: "main"               # Source branch from Original Repo (O)
          destination_branch: "production"    # Destination branch on Fork Repo (F)
          github_token: ${{ secrets.PAT_TOKEN }}